'use strict';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');
let saved={level:1,unlocked:1,done:[],skipped:[]};try{const d=JSON.parse(localStorage.getItem('rota-v1'));if(d&&Number.isInteger(d.unlocked)&&d.unlocked>=1&&d.unlocked<=100){saved={level:Math.max(1,Math.min(d.level||1,d.unlocked)),unlocked:d.unlocked,done:(d.done||[]).filter(x=>Number.isInteger(x)&&x>=1&&x<=100),skipped:(d.skipped||[]).filter(x=>Number.isInteger(x)&&x>=1&&x<=100)}}}catch{}
let current=saved.level,data,path,collected,won=false,dragging=false,hintEdge=null,hintTimer,sound=false,audio;
const worlds=['İlk adımlar','Küçük keşifler','Yeni kıvrımlar','Sakin akış','Son ışıklar'];
function persist(){saved.level=current;try{localStorage.setItem('rota-v1',JSON.stringify(saved))}catch{$('save-status').textContent='Bu tarayıcı ilerleme kaydına izin vermiyor.'}}
function beep(win=false){if(!sound)return;try{audio||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=win?660:440;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.23);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.24)}catch{}}
function start(level){if(!Number.isInteger(level)||level<1||level>saved.unlocked)throw Error('Bu bölüm henüz açık değil.');current=level;data=levelData(level);path=[0];collected=new Set();won=false;hintEdge=null;clearTimeout(hintTimer);$('win').hidden=true;const world=worlds[Math.floor((level-1)/20)];$('world').textContent=String(Math.floor((level-1)/20)+1).padStart(2,'0')+' / '+world.toLocaleUpperCase('tr');$('chapter').textContent=world;$('level').textContent=String(level).padStart(2,'0');$('progress').style.width=saved.done.length+'%';$('completed').textContent=saved.done.length?`${saved.done.length} bölüm tamamlandı.`:'Yolculuğun burada başlıyor.';$('hint').textContent=level===1?'Yeşil noktadan başla, parmağınla yolu çiz.':'Işıkları topla ve mor halkaya ulaş.';persist();draw()}
function geometry(){const w=canvas.clientWidth;return {w,p:w*.085,cell:w*.83/data.n}}
function position(a){const {p,cell}=geometry();return [p+(a%data.n+.5)*cell,p+(Math.floor(a/data.n)+.5)*cell]}
function draw(){if(!data)return;const {w,p,cell}=geometry(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(w*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,w);ctx.lineCap='round';ctx.lineJoin='round';
 for(let a=0;a<data.n*data.n;a++){const [x,y]=position(a);ctx.fillStyle='#8394aa35';ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill();const col=a%data.n,row=Math.floor(a/data.n);ctx.strokeStyle='#566779';ctx.lineWidth=3;
 if(col<data.n-1&&!data.edges[a].includes(a+1)){const bx=p+(col+1)*cell;ctx.beginPath();ctx.moveTo(bx,p+row*cell+cell*.18);ctx.lineTo(bx,p+(row+1)*cell-cell*.18);ctx.stroke()}
 if(row<data.n-1&&!data.edges[a].includes(a+data.n)){const by=p+(row+1)*cell;ctx.beginPath();ctx.moveTo(p+col*cell+cell*.18,by);ctx.lineTo(p+(col+1)*cell-cell*.18,by);ctx.stroke()}}
 if(path.length>1){ctx.strokeStyle='#d7fa78';ctx.lineWidth=cell*.17;ctx.shadowBlur=16;ctx.shadowColor='#d7fa7833';ctx.beginPath();path.forEach((a,i)=>{const [x,y]=position(a);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.shadowBlur=0}
 if(hintEdge){ctx.strokeStyle='#d7fa7888';ctx.lineWidth=4;ctx.setLineDash([3,8]);ctx.beginPath();ctx.moveTo(...position(hintEdge[0]));ctx.lineTo(...position(hintEdge[1]));ctx.stroke();ctx.setLineDash([])}
 const [gx,gy]=position(data.goal);ctx.strokeStyle='#b9a2ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(gx,gy,cell*.23,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b9a2ff';ctx.beginPath();ctx.arc(gx,gy,cell*.07,0,Math.PI*2);ctx.fill();
 for(const gem of data.gems){if(collected.has(gem))continue;const [x,y]=position(gem),r=cell*.14;ctx.fillStyle='#f9cc85';ctx.shadowBlur=18;ctx.shadowColor='#f9cc8560';ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();ctx.fill();ctx.shadowBlur=0}
 const [sx,sy]=position(path.at(-1));ctx.fillStyle='#d7fa7815';ctx.beginPath();ctx.arc(sx,sy,cell*.37,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d7fa78';ctx.beginPath();ctx.arc(sx,sy,cell*.23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#26352a';ctx.beginPath();ctx.arc(sx,sy,cell*.065,0,Math.PI*2);ctx.fill();$('count').textContent=`${collected.size} / ${data.gems.length} ışık`;
}
function move(to){if(won||!data.edges[path.at(-1)].includes(to))return false;const index=path.indexOf(to);if(index>=0)path=path.slice(0,index+1);else path.push(to);hintEdge=null;if(data.gems.includes(to)&&!collected.has(to)){collected.add(to);beep()}draw();if(to===data.goal){if(collected.size===data.gems.length)finish(false);else $('hint').textContent='Hedef burası. Önce kalan ışıkları topla.'}else $('hint').textContent='Geri dönmek için önceki noktaya ilerleyebilirsin.';return true}
function finish(skipped){won=true;if(skipped){if(!saved.skipped.includes(current))saved.skipped.push(current)}else{if(!saved.done.includes(current))saved.done.push(current);saved.skipped=saved.skipped.filter(x=>x!==current);beep(true)}saved.unlocked=Math.min(100,Math.max(saved.unlocked,current+1));persist();const end=current===100;$('win-label').textContent=end?'100 / 100 · YOLCULUĞUN SONU':skipped?'BÖLÜM ATLANDI':'BÖLÜM TAMAMLANDI';$('win-title').textContent=end?'Yolun sonuna geldin.':skipped?'Yeni bir yol açıldı.':'Güzel bir rota.';$('win-text').textContent=end?`${saved.done.length} bölüm çözüldü, ${saved.skipped.length} bölüm atlandı. Dilediğin bölüme geri dönebilirsin.`:skipped?'İstersen bu bölüme daha sonra geri dönebilirsin.':'Bir sonraki küçük yolculuğa hazır mısın?';$('next').innerHTML=end?'Bölümlere dön <span>▦</span>':'Sonraki bölüm <span>→</span>';$('win').hidden=false;$('hint').textContent=end?'100 bölümlük yolculuk bitti.':'Her yol bir adımla başlar.';$('progress').style.width=saved.done.length+'%';$('completed').textContent=`${saved.done.length} bölüm tamamlandı.`}
function hit(e){const r=canvas.getBoundingClientRect(),{p,cell}=geometry();const c=Math.floor((e.clientX-r.left-p)/cell),row=Math.floor((e.clientY-r.top-p)/cell);return c>=0&&c<data.n&&row>=0&&row<data.n?row*data.n+c:-1}
canvas.addEventListener('pointerdown',e=>{if(won)return;e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);dragging=true;const a=hit(e);if(a>=0)move(a)});canvas.addEventListener('pointermove',e=>{if(dragging){e.preventDefault();const a=hit(e);if(a>=0)move(a)}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>dragging=false);
canvas.addEventListener('keydown',e=>{const a=path.at(-1),n=data.n,map={ArrowUp:a-n,ArrowDown:a+n,ArrowLeft:a-1,ArrowRight:a+1};if(e.key in map){e.preventDefault();move(map[e.key])}});
$('reset').onclick=()=>start(current);$('replay').onclick=()=>start(current);$('next').onclick=()=>current===100?showLevels():start(current+1);$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Ses açık':'Ses kapalı';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Sesi kapat':'Sesi aç');beep()};
$('help').onclick=()=>{if(won)return;const from=path.at(-1),targets=data.gems.filter(x=>!collected.has(x));if(!targets.length)targets.push(data.goal);const q=[from],prev=new Map([[from,null]]);let target;for(let i=0;i<q.length;i++){const a=q[i];if(targets.includes(a)){target=a;break}for(const b of data.edges[a])if(!prev.has(b)){prev.set(b,a);q.push(b)}}if(target===undefined)return;let step=target;while(prev.get(step)!==from&&prev.get(step)!==null)step=prev.get(step);hintEdge=[from,step];$('hint').textContent='Kesik çizgiyi takip et. İpuçları her zaman ücretsiz.';draw();clearTimeout(hintTimer);hintTimer=setTimeout(()=>{hintEdge=null;draw()},5000)};
const modal=$('modal');function openModal(title){$('modal-title').textContent=title;if(!modal.open)modal.showModal()}$('close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function showLevels(){const content=$('modal-content');content.innerHTML='<p class="note">100 küçük yolculuk. Bitirdiğin bölümleri yeniden oynayabilirsin.</p><div class="level-grid"></div>';const grid=content.querySelector('.level-grid');for(let i=1;i<=100;i++){const b=document.createElement('button');const done=saved.done.includes(i),skip=saved.skipped.includes(i);b.textContent=String(i).padStart(2,'0');const small=document.createElement('small');small.textContent=done?'Çözüldü':skip?'Atlandı':i>saved.unlocked?'Kilitli':i===current?'Buradasın':'Açık';b.append(small);b.className=(done?'done ':'')+(i===current?'current':'');b.disabled=i>saved.unlocked;b.onclick=()=>{modal.close();start(i)};grid.append(b)}openModal('Yolculuğun');setTimeout(()=>grid.children[current-1].scrollIntoView({block:'nearest'}),50)}$('levels').onclick=showLevels;
$('skip').onclick=()=>{if(won)return;$('modal-content').innerHTML='<p>Bu bölümü atlayıp bir sonrakini açabilirsin. Atlanan bölümler çözülmüş sayılmaz; daha sonra geri dönebilirsin.</p><p><strong>Demo sürümü — ödeme alınmaz.</strong></p><p class="note">Tam sürümde yalnızca bölüm atlama ücretli olacak. Güç, can veya VIP satışı olmayacak. Tüm bölümler oynayarak ücretsiz açılır.</p><button id="confirm-skip" class="primary">Ücretsiz demo atlaması</button><button id="cancel-skip" class="textbutton">Oynamaya devam et</button>';openModal('Bu yolu pas geç?');$('confirm-skip').onclick=()=>{modal.close();finish(true)};$('cancel-skip').onclick=()=>modal.close()};
new ResizeObserver(draw).observe(canvas.parentElement);start(current);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_rota_progress',description:'Oyunun mevcut bölümünü ve bu cihazdaki ilerlemeyi okur.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({level:current,unlocked:saved.unlocked,completed:saved.done.length,skipped:saved.skipped.length,lights:collected.size,finished:won})})).catch(()=>{})}catch{}}
